# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-10 02:09

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("api", "0004_auto_20160929_0317"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable(
                    name="task",
                    table="tasks_task",
                ),
            ],
        ),
    ]
