# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-10 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_action_auto_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='state',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
