# Generated by Django 3.2.16 on 2022-12-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0004_auto_20190610_0209"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="auto_approve",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
